apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fcg-user
  template:
    metadata:
      labels:
        app: fcg-user
    spec:
      containers:
      - name: users
        image: PLACEHOLDER_ECR_REPOSITORY:latest
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: fcg-ms-user-secret
              key: ConnectionStrings__DefaultConnection
        - name: UserNotification__Uri
          valueFrom:
            secretKeyRef:
              name: fcg-ms-user-secret
              key: UserNotification__Uri
